spring:
  profiles:
    active:
      - local
    group:
      local: "site-local, db-local"
      dev: "site-dev"
    include:
      - db
      - site
my.service:
  enabled: false
  remote-address: 192.168.0.1
  securtity:
    username: honeymon
    password: 810301
    roles:
      - USER
      - ADMIN
    attrs:
      hasWriteAuthority: false
      hasReadAuthority: true
      hasDeleteAuthority: false